# see LICENSE file for attribution

# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'etcd-lab'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.


  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
         - targets: ['localhost:9090']


  - job_name: 'etcd'
    scrape_interval: 1s
    honor_labels: true

    dns_sd_configs:
    - names:
      - 'tasks.etcd-1'
      - 'tasks.etcd-2'
      - 'tasks.etcd-3'
      type: 'A'
      port: 2379

    static_configs:
      - targets:
        - 'etcd-1:2379'
        - 'etcd-2:2379'
        - 'etcd-3:2379'
